# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/refs/heads/main/schema/markdownlint-config-schema.json
extends: ../.markdownlint.yaml
first-line-heading: false
no-hard-tabs:
  code_blocks: false
